name: wf-deploy-pr

on:
  pull_request:
    branches:
      - develop

jobs:
  wf-develop-build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Website
        run: |
          npx parcel build "./src/index.html" --dist-dir "./dist" --public-url "./"

      - name: Upload artifacts 
        uses: actions/upload-pages-artifacts@v3
        with:
          path: "./dist"
          name: "develop-artifacts"   

  wf-develop-deploy-job:
    needs: wf-develop-build-job
    permissions: 
      pages: write
      id_token: write
    environment: "development-env"
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Build Artifacts on GitHub Pages
        uses: actions/deploy-pages@v4
        with: 
          artifact_name: "develop-artifacts"
          token: ${{ github.token }}
